# TODO a way to configure dev and prod
# all rtgl fe configuration

ui:
  svg:
    dir: "ui/svg"
    outfile: "vt/static/public/rtgl-icons.js"

fe:
  dirs: ["fe/pages"] # directories that contain components
  setup: "fe/setup.js" # path to setup.js file
  outfile: "static/public/main.js" # output this is separate from rettangoli file
  #  watchPort: 3001

# all sites configuration
# sites:
#   path: 'sites'
#   templateFolder: '..'

# all visual testing configuration
vt:
  path: "vt"
  name: "Example1 Visual Tests"
  description: "Visual testing for example1 project"
  sections:
    - title: "Todos"
      files: "pages/todos"
      description: "Todos Page"
