imports:
  templates:
    base: https://cdn.jsdelivr.net/npm/@rettangoli/sites@1.0.0-rc9/sites/templates/base.yaml
    docs: https://cdn.jsdelivr.net/npm/@rettangoli/sites@1.0.0-rc9/sites/templates/docs.yaml
  partials:
    seo: https://cdn.jsdelivr.net/npm/@rettangoli/sites@1.0.0-rc9/sites/partials/seo.yaml
    navbar: https://cdn.jsdelivr.net/npm/@rettangoli/sites@1.0.0-rc9/sites/partials/navbar.yaml
    mobile-nav: https://cdn.jsdelivr.net/npm/@rettangoli/sites@1.0.0-rc9/sites/partials/mobile-nav.yaml
    docs-sidebar: https://cdn.jsdelivr.net/npm/@rettangoli/sites@1.0.0-rc9/sites/partials/docs-sidebar.yaml

markdownit:
  html: true
  linkify: true
  typographer: false
  shiki:
    enabled: true
    theme: slack-dark
  codePreview:
    enabled: true
    showSource: true
    theme: slack-dark
  headingAnchors:
    enabled: true
    slugMode: ascii
    wrap: true
    fallback: section
build:
  keepMarkdownFiles: true
